version: '3'

services:
# Apache, PHP
  server:
    container_name: training-book-reader
    build: ./docker/server
    volumes:
      - ./server:/srv:rw
    expose:
      - 9000
    ports:
      - 80:80
      - 443:443
    privileged: true
    working_dir: /srv

# Database MySQL
  db:
    image: mysql:5.7
    container_name: training-book-reader-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Ho_Chi_Minh'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

# Composer
  composer:
    container_name: training-book-reader-composer
    image: composer:1.6
    command: 'composer install'
    volumes:
      - ./server:/var/www:rw
    working_dir: /var/www

# phpMyAdmin
  phpmyadmin:
    container_name: training-book-reader-myadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=training-book-reader-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
    - 8080:80
